### ISSUE TITLE
Error when trying to verify an empty repo 

### ISSUE THREAD

**Issue by oiime** [RedpointGames/pkgsign#8]
```
± pkgsign verify . --full
package verification summary:
0 compromised
1 unsigned
0 untrusted
1 trusted

TypeError: Cannot read property 'length' of undefined
    at padRight (/usr/local/lib/node_modules/pkgsign/dist/commands/verify.js:219:34)
    at default_1.<anonymous> (/usr/local/lib/node_modules/pkgsign/dist/commands/verify.js:242:33)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/pkgsign/dist/commands/verify.js:16:58)
    at <anonymous>
```

**Comment by hach-que** [comment]
Resolved in the `dev` branch and will be released as part of `0.2.0`.
